/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Administrator
 */
public class AddList extends java.awt.Dialog {

    private int planId = 0;
    private Date startDate;
    private Date endDate;
    MyPlan mp;
    Connection conn = null;
    PreparedStatement pstm = null;
    private int day;

    public int getDay() {
        return day;
    }

    public void setDay(int day) {
        this.day = day;
    }

    public int getPlanId() {
        return planId;
    }

    public void setPlanId(int planId) {
        this.planId = planId;

    }

    /**
     * Creates new form AddList1
     */
    public AddList(java.awt.Frame parent, boolean modal, MyPlan mp, int planId, Date startDate, Date endDate) {
        super(parent, modal);
        try {
            this.planId = planId;
            this.startDate = startDate;
            this.endDate = endDate;
            initComponents();
            this.mp = mp;
            txtListPlanId.setText(this.planId + "");
            txtListPlanId.setVisible(false);
            System.out.println(mp.getPlanName());
            conn = MySQLConnect.getMySQLConnection();
            chooseDayFromComboBox();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addList = new javax.swing.JLabel();
        lblDes = new javax.swing.JLabel();
        lblReps = new javax.swing.JLabel();
        txtList = new javax.swing.JTextField();
        txtDes = new javax.swing.JTextField();
        txtReps = new javax.swing.JTextField();
        txtSet = new javax.swing.JTextField();
        lblday = new javax.swing.JLabel();
        lblList = new javax.swing.JLabel();
        lblSet = new javax.swing.JLabel();
        boxChooseDay = new javax.swing.JComboBox<>();
        txtListPlanId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        lblsave = new javax.swing.JLabel();
        cancelBtn1 = new javax.swing.JButton();
        lblcancel = new javax.swing.JLabel();
        noti1 = new javax.swing.JLabel();
        noti2 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        addList.setFont(new java.awt.Font("Century Gothic", 1, 32)); // NOI18N
        addList.setForeground(new java.awt.Color(255, 255, 255));
        addList.setText("Add List");

        lblDes.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblDes.setForeground(new java.awt.Color(255, 255, 255));
        lblDes.setText("Description");

        lblReps.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblReps.setForeground(new java.awt.Color(255, 255, 255));
        lblReps.setText("Reps");

        txtList.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtListFocusLost(evt);
            }
        });

        txtDes.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtDes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDesFocusLost(evt);
            }
        });

        txtReps.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtReps.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRepsFocusLost(evt);
            }
        });

        txtSet.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtSet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSetFocusLost(evt);
            }
        });

        lblday.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblday.setForeground(new java.awt.Color(255, 255, 255));
        lblday.setText("Day");

        lblList.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblList.setForeground(new java.awt.Color(255, 255, 255));
        lblList.setText("List name");

        lblSet.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblSet.setForeground(new java.awt.Color(255, 255, 255));
        lblSet.setText("Set");

        boxChooseDay.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        boxChooseDay.setModel(new javax.swing.DefaultComboBoxModel<>());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Santex/image/clipboard (1).png"))); // NOI18N

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Santex/image/diskette.png"))); // NOI18N
        saveBtn.setBorderPainted(false);
        saveBtn.setContentAreaFilled(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        lblsave.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lblsave.setForeground(new java.awt.Color(255, 255, 255));
        lblsave.setText(" SAVE ");
        lblsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsaveMouseClicked(evt);
            }
        });

        cancelBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Santex/image/file (4).png"))); // NOI18N
        cancelBtn1.setBorderPainted(false);
        cancelBtn1.setContentAreaFilled(false);
        cancelBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtn1ActionPerformed(evt);
            }
        });

        lblcancel.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lblcancel.setForeground(new java.awt.Color(255, 255, 255));
        lblcancel.setText("CANCEL");
        lblcancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcancelMouseClicked(evt);
            }
        });

        noti1.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        noti1.setVisible(false);
        noti1.setForeground(new java.awt.Color(255, 0, 0));
        noti1.setText("*please enter number between 1 to 100");

        noti2.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        noti2.setVisible(false);
        noti2.setForeground(new java.awt.Color(255, 0, 0));
        noti2.setText("*please enter number between 1 to 100");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblsave)
                                .addGap(13, 13, 13))
                            .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(194, 194, 194)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcancel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addList, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblday, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblList)
                            .addComponent(lblDes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtList)
                                .addComponent(boxChooseDay, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDes, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblReps)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtReps, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSet, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(233, 233, 233)
                        .addComponent(txtListPlanId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noti1)
                            .addComponent(noti2))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(addList)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(boxChooseDay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txtDes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(lblday, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblList))
                        .addGap(43, 43, 43)
                        .addComponent(lblDes)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblReps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReps))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noti1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblSet))
                    .addComponent(txtSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noti2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(txtListPlanId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblsave, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    public void addAddListToDetailListOfMyPlan() {
        try {
            System.out.println("Clicked Save button");

            if (txtList.getText().equals("") || txtDes.getText().equals("") || txtReps.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Your input is incorrect");
            } else {
                String sqlList = "insert into LIST(listName,descriptionList,reps,`set`,list_planID,list_nameDay)"
                        + " values (?,?,?,?,?,?)";
                pstm = conn.prepareStatement(sqlList);
                pstm.setString(1, txtList.getText());
                pstm.setString(2, txtDes.getText());
                pstm.setString(3, txtReps.getText());
                String r = txtReps.getText();
                int reps = Integer.parseInt(r);
                pstm.setString(4, txtSet.getText());
                String s = txtSet.getText();
                int set = Integer.parseInt(s);
                pstm.setString(5, txtListPlanId.getText());
                pstm.setString(6, boxChooseDay.getSelectedItem() + "");
                String l = txtListPlanId.getText();
                int listPlanId = Integer.parseInt(l);
                pstm.executeUpdate();
                JOptionPane.showMessageDialog(null, "Add list successfully");
                MyPlan frame = new MyPlan();
                frame.setVisible(true);
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setLocationRelativeTo(null);
                frame.setResizable(false);
                setVisible(false);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    public void backToMyPlan() {
        System.out.println("Clicked Cancel button");
        MyPlan mp = new MyPlan();
        mp.setVisible(true);
        mp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mp.setLocationRelativeTo(null);
        mp.setResizable(false);
        setVisible(false);
    }

    public void checkUserInputReps() {
        int input;
        try {
            input = Integer.parseInt(txtReps.getText());
            if (input == 0) {
                txtReps.setText("");
                noti1.setVisible(true);
            } else if (input > 0 && input <= 100) {
                noti1.setVisible(false);
            } else {
                noti1.setVisible(true);
                txtReps.setText("");
            }
        } catch (NumberFormatException ex) {
            txtReps.setText("");
            noti1.setVisible(true);
        }
    }

    public void checkUserInputSet() {
        int input;
        try {
            input = Integer.parseInt(txtSet.getText());
            if (input == 0) {
                txtSet.setText("");
                noti2.setVisible(true);
            } else if (input > 0 && input <= 100) {
                noti2.setVisible(false);
            } else {
                noti2.setVisible(true);
                txtSet.setText("");
            }
        } catch (NumberFormatException ex) {
            txtSet.setText("");
            noti2.setVisible(true);
        }
    }

    public void checkUserInputListName() {
        if (!(Pattern.matches("^[a-zA-Z0-9 ]+$", txtList.getText()))) {
            txtList.setText("");
        }
    }

    public void checkUserInputListDescription() {
        if (!(Pattern.matches("^[a-zA-Z0-9 ]+$", txtDes.getText()))) {
            txtDes.setText("");
        }
    }

    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        addAddListToDetailListOfMyPlan();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtn1ActionPerformed
        backToMyPlan();
    }//GEN-LAST:event_cancelBtn1ActionPerformed

    private void lblsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsaveMouseClicked
        addAddListToDetailListOfMyPlan();
    }//GEN-LAST:event_lblsaveMouseClicked

    private void lblcancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcancelMouseClicked
        backToMyPlan();
    }//GEN-LAST:event_lblcancelMouseClicked

    private void txtRepsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRepsFocusLost
        checkUserInputReps();
    }//GEN-LAST:event_txtRepsFocusLost

    private void txtSetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSetFocusLost
        checkUserInputSet();
    }//GEN-LAST:event_txtSetFocusLost

    private void txtListFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtListFocusLost
        checkUserInputListName();
    }//GEN-LAST:event_txtListFocusLost

    private void txtDesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDesFocusLost
        checkUserInputListDescription();
    }//GEN-LAST:event_txtDesFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

//                AddList dialog = new AddList(new java.awt.Frame(), true, new MyPlan(), planId,startDate,endDate);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
            }
        });
    }

    public void chooseDayFromComboBox() {
        try {
            System.out.println("selecting.." + planId);
            pstm = conn.prepareStatement("SELECT nameDay,dayperweek from PLAN where planID = " + planId);
            System.out.println("Dai laew na");
            ResultSet rs = pstm.executeQuery();
            while (rs.next()) {
                String days = rs.getString("nameDay");
                int start = 0;
                for (int i = 0; i < rs.getInt("dayperweek"); i++) {
                    String eachDay = days.substring(start, days.indexOf(" ", start));
                    start = days.indexOf(" ", start) + 1;
                    boxChooseDay.addItem(eachDay);
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addList;
    private javax.swing.JComboBox<String> boxChooseDay;
    private javax.swing.JButton cancelBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDes;
    private javax.swing.JLabel lblList;
    private javax.swing.JLabel lblReps;
    private javax.swing.JLabel lblSet;
    private javax.swing.JLabel lblcancel;
    private javax.swing.JLabel lblday;
    private javax.swing.JLabel lblsave;
    private javax.swing.JLabel noti1;
    private javax.swing.JLabel noti2;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField txtDes;
    private javax.swing.JTextField txtList;
    private javax.swing.JTextField txtListPlanId;
    private javax.swing.JTextField txtReps;
    private javax.swing.JTextField txtSet;
    // End of variables declaration//GEN-END:variables
}
