/*/
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

//import com.mysql.jdbc.PreparedStatement;
import com.toedter.calendar.JCalendar;
import java.awt.Color;
import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class MyPlan extends javax.swing.JFrame {

    DefaultTableModel model;
    Connection conn = null;
    PreparedStatement pstm1 = null;
    PreparedStatement pstm2 = null;
    private String planName;
    private String planDes;
    private Date startDate;
    private Date endDate;
    private int dayPerWeek;
    private String nameDay;
    private int planId;
    private int list_planID;
    private int planStatus;

    public int getPlanStatus() {
        return planStatus;
    }

    public void setPlanStatus(int planStatus) {
        this.planStatus = planStatus;
    }

    public int getList_planID() {
        return list_planID;
    }

    public void setList_planID(int list_planID) {
        this.list_planID = list_planID;
    }

    public int getPlanId() {
        return planId;
    }

    public void setPlanId(int planId) {
        this.planId = planId;
    }

    public String getPlanName() {
        return planName;
    }

    public void setPlanName(String planName) {
        this.planName = planName;
    }

    public String getPlanDes() {
        return planDes;
    }

    public void setPlanDes(String planDes) {
        this.planDes = planDes;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public int getDayPerWeek() {
        return dayPerWeek;
    }

    public void setDayPerWeek(int dayPerWeek) {
        this.dayPerWeek = dayPerWeek;
    }

    public String getNameDay() {
        return nameDay;
    }

    public void setNameDay(String nameDay) {
        this.nameDay = nameDay;
    }

    /**
     * Creates new form MyPlan2
     */
    public MyPlan() {
        try {
            initComponents();
            conn = MySQLConnect.getMySQLConnection();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        myPlan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblEnd = new javax.swing.JLabel();
        txtEnd = new javax.swing.JLabel();
        lblStart = new javax.swing.JLabel();
        txtStart = new javax.swing.JLabel();
        lblDPW = new javax.swing.JLabel();
        lblDes = new javax.swing.JLabel();
        lblPName = new javax.swing.JLabel();
        lbledit = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        lbldelete = new javax.swing.JLabel();
        lblstatus = new javax.swing.JLabel();
        txtStatusPlan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDPW = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPName = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDes = new javax.swing.JLabel();
        lblAdd = new javax.swing.JLabel();
        lblDetail = new javax.swing.JLabel();
        lblstart = new javax.swing.JLabel();
        addListBtn = new javax.swing.JButton();
        detailListBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        lblcreate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1341, 710));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("My Plan");

        myPlan.setFont(new java.awt.Font("Yu Gothic Light", 0, 15)); // NOI18N
        myPlan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Plan Name", "Description Plan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        myPlan.setToolTipText("");
        myPlan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myPlanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(myPlan);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(402, 700));

        lblEnd.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblEnd.setText("End Date");

        txtEnd.setFont(new java.awt.Font("Yu Gothic Light", 1, 17)); // NOI18N

        lblStart.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblStart.setText("Start Date");

        txtStart.setFont(new java.awt.Font("Yu Gothic Light", 1, 17)); // NOI18N

        lblDPW.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblDPW.setText("Day per Week");

        lblDes.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblDes.setText("Description");

        lblPName.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblPName.setText("Plan Name");

        lbledit.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lbledit.setText("EDIT");
        lbledit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbleditMouseClicked(evt);
            }
        });

        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Santex/image/writer.png"))); // NOI18N
        editBtn.setContentAreaFilled(false);
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Santex/image/remove.png"))); // NOI18N
        deleteBtn.setContentAreaFilled(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        lbldelete.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lbldelete.setText("DELETE ");
        lbldelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldeleteMouseClicked(evt);
            }
        });

        lblstatus.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblstatus.setText("Status Plan");

        txtStatusPlan.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N

        txtDPW.setBackground(new java.awt.Color(255, 255, 255));
        txtDPW.setFont(new java.awt.Font("Yu Gothic Light", 1, 17)); // NOI18N
        jScrollPane1.setViewportView(txtDPW);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        txtPName.setBackground(new java.awt.Color(255, 255, 255));
        txtPName.setFont(new java.awt.Font("Yu Gothic Light", 1, 17)); // NOI18N
        txtPName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setViewportView(txtPName);

        txtDes.setBackground(new java.awt.Color(255, 255, 255));
        txtDes.setFont(new java.awt.Font("Yu Gothic Light", 1, 17)); // NOI18N
        jScrollPane4.setViewportView(txtDes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbledit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(119, 119, 119)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldelete, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDPW)
                            .addComponent(lblDes)
                            .addComponent(lblPName)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStart)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblEnd)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblstatus)
                                    .addGap(45, 45, 45)
                                    .addComponent(txtStatusPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblPName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDPW)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEnd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStatusPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblstatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(editBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbledit))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(deleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbldelete)))
                .addGap(38, 38, 38))
        );

        lblAdd.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lblAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd.setText("ADD LIST PLAN");
        lblAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddMouseClicked(evt);
            }
        });

        lblDetail.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lblDetail.setForeground(new java.awt.Color(255, 255, 255));
        lblDetail.setText("DETAIL LIST PLAN");
        lblDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDetailMouseClicked(evt);
            }
        });

        lblstart.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lblstart.setForeground(new java.awt.Color(255, 255, 255));
        lblstart.setText("START PLAN");
        lblstart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblstartMouseClicked(evt);
            }
        });

        addListBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Santex/image/file (2).png"))); // NOI18N
        addListBtn.setContentAreaFilled(false);
        addListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addListBtnActionPerformed(evt);
            }
        });

        detailListBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Santex/image/contract (1).png"))); // NOI18N
        detailListBtn.setContentAreaFilled(false);
        detailListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailListBtnActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Santex/image/strategy (2).png"))); // NOI18N

        startBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Santex/image/muscles (1).png"))); // NOI18N
        startBtn.setContentAreaFilled(false);
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        homeBtn.setBackground(new java.awt.Color(102, 102, 102));
        homeBtn.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Santex/image/wall-calendar.png"))); // NOI18N
        homeBtn.setContentAreaFilled(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" HOME ");

        createBtn.setBackground(new java.awt.Color(102, 102, 102));
        createBtn.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        createBtn.setForeground(new java.awt.Color(255, 255, 255));
        createBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Santex/image/archive.png"))); // NOI18N
        createBtn.setContentAreaFilled(false);
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        lblcreate.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lblcreate.setForeground(new java.awt.Color(255, 255, 255));
        lblcreate.setText("CREATE PLAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblcreate)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(addListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)))
                            .addGap(83, 83, 83)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDetail)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(detailListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(94, 94, 94)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblstart)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(234, 234, 234)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel1))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(addListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(detailListBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDetail))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(startBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblstart))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcreate)))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void showMyPlanTable() {
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date date = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("EEEE");
            model = (DefaultTableModel) myPlan.getModel();
            model.setRowCount(0); //บอกว่าแถวแรกของตารางเป็น 0
            String sql = "select * from PLAN WHERE endDate>=?";
            pstm1 = conn.prepareStatement(sql);
            pstm1.setString(1, dateFormat.format(date.getTime()));

            ResultSet rs = pstm1.executeQuery();
            while (rs.next()) {
                //เก็บ planId,planName,descrip,totaldays ในทุกๆช่องลงในตัวแปร planId ทีเป็นArrayList เพราะเราไม่รู้จำนวนที่แน่นอน
                Vector v = new Vector();
                v.add(rs.getString("planName"));
                v.add(rs.getString("descriptionPlan"));
                v.add(rs.getInt("planId"));
                model.addRow(v);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();

        }
    }

    public void clickMyPlanTable() {
        try {
            System.out.println("Clicked MyPlan");
            txtPName.setText(myPlan.getValueAt(myPlan.getSelectedRow(), 0) + "");
            txtDes.setText(myPlan.getValueAt(myPlan.getSelectedRow(), 1) + "");
            String sql = "select * from PLAN where planName=?";
            pstm1 = conn.prepareStatement(sql);
            pstm1.setString(1, myPlan.getValueAt(myPlan.getSelectedRow(), 0) + "");
            ResultSet rs = pstm1.executeQuery();
            while (rs.next()) {
                txtDPW.setText(rs.getString("nameDay"));
                txtStart.setText(rs.getDate("startDate").toString());
                txtEnd.setText(rs.getDate("endDate").toString());
                txtPName.setText(rs.getString("planName"));
                if (rs.getInt("planStatus") == 1) {
                    txtStatusPlan.setText("Starting");
                    txtStatusPlan.setForeground(new java.awt.Color(51, 255, 51));
                    lblAdd.setEnabled(false);
//                    lblDetail.setEnabled(false);
                    lblstart.setEnabled(false);
                } else if (rs.getInt("planStatus") == 0) {
                    txtStatusPlan.setText("Not start");
                    txtStatusPlan.setForeground(new java.awt.Color(255, 0, 0));
                    lblAdd.setEnabled(true);
                    lblDetail.setEnabled(true);
                    lblstart.setEnabled(true);
                } else if (rs.getInt("planStatus") == 2) {

                }
                setPlanStatus(rs.getInt("planStatus"));
                setPlanName(rs.getString("planName"));
                setPlanDes(rs.getString("descriptionPlan"));
                setNameDay(rs.getString("nameDay"));
                setStartDate(rs.getDate("startDate"));
                setEndDate(rs.getDate("endDate"));
                setPlanId(rs.getInt("planId"));
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    public void editMyPlan() {
        if (getPlanStatus() == 1) {
            System.out.println("No");
            showMessageDialog(null, "Your plan is starting!!");
        } else if (getPlanStatus() == 0) {
            if (getPlanId() == 0) {
                JOptionPane.showMessageDialog(null, "Pleas choose Plan");
            } else {
                System.out.println("Clicked Edit button");
                EditPlan eplan = new EditPlan(getPlanId(), getPlanName(), getPlanDes(),
                        getStartDate(), getEndDate(), getDayPerWeek(), getNameDay());
                System.out.println(getPlanId());
                eplan.setVisible(true);
                eplan.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                eplan.setLocationRelativeTo(null);
                this.setVisible(false);
            }
        }
    }

    public void deleteMyPlan() {
        try {
            if (getPlanId() == 0) {
                JOptionPane.showMessageDialog(null, "Pleas choose Plan");
            } else {
                System.out.println("Clicked delete");
                System.out.println("list_planID " + list_planID);
                System.out.println("planId " + planId);
                Object[] options = {"Yes", "No"}; //เป็นปุ่มที่ให้เลือกว่าจะกดอะไร
                int n = JOptionPane.showOptionDialog(deleteBtn, //1.เป็นชนิดของปุ่ม
                        "Do you want delete plan?", //2.เป็นข้อความโชว์บนกล่อง message
                        "Delete Plan!!!", //3.title ของ message box
                        JOptionPane.YES_NO_CANCEL_OPTION, //4.ชนิดของ optionPane ว่าเป็น yes/no
                        JOptionPane.QUESTION_MESSAGE,
                        null, //ไม่ใช้ไอคอน do not use a custom Icon
                        options, //ชื่อของในแต่ละปุ่ม the titles of button ที่มี yes no
                        options[0]); //default button title
                // ถ้ากด yes จะทำให้ n มีค่าเป็น 0
                if (n == 0) {
                    String sql = "delete from LIST where list_planID =" + planId;
                    pstm1 = conn.prepareStatement(sql);
                    pstm1.executeUpdate();
                    String sql2 = "delete from PLAN where planId=" + planId;
                    pstm2 = conn.prepareStatement(sql2);
                    pstm2.executeUpdate();
                    //ให้มันแสดงเฉยๆว่าแพลนนั้นถูกลบออกไปแล้วแต่กดเลือกอะไรไม่ได้นอกจากแค่กด ok หรือปิดหน้าจอไป
                    JOptionPane.showMessageDialog(null, "Your plan is deleted");

                    repaint();
                } else {
                    System.out.println("Canceled");
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    public void addAddListToDetailOfMyPlan() {
        if (getPlanStatus() == 1) {
            System.out.println("No");
            showMessageDialog(null, "Your plan is starting!!");
        } else if (getPlanStatus() == 0) {
            if (getPlanId() == 0) {
                JOptionPane.showMessageDialog(null, "Pleas choose Plan");
            } else {
                System.out.println("Clicked Addlist button");
                System.out.println("" + getPlanId());
                AddList al = new AddList(this, rootPaneCheckingEnabled, this, getPlanId(), getStartDate(), getEndDate());
                al.setVisible(true);
            }
        }
    }

    private void clickToDetailList() {
        if (getPlanStatus() == 1) {
            showMessageDialog(null, "Your plan is starting!!");
            DetailList dl = new DetailList(getPlanId(), getPlanStatus());
            EditList edlp = new EditList(getPlanId());
            System.out.println(getPlanId());
            dl.setVisible(true);
            dl.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            dl.setLocationRelativeTo(null);
            setVisible(false);
        } else if (getPlanStatus() == 0) {
            if (getPlanId() == 0) {
                JOptionPane.showMessageDialog(null, "Pleas choose Plan");
            } else {
                System.out.println("Clicked DetailList button");
                DetailList dl = new DetailList(getPlanId(), getPlanStatus());
                EditList edlp = new EditList(getPlanId());
                System.out.println(getPlanId());
                dl.setVisible(true);
                setVisible(false);
                dl.setLocationRelativeTo(null);
                dl.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            }
        }
    }

    public void updateStatusPlan(int id) {
        try {
            if (getPlanId() == 0) {
                JOptionPane.showMessageDialog(null, "Pleas choose Plan");
            } else {
                System.out.println("SQL");
                System.out.println("" + id);
                String sql = "update PLAN set planStatus =? where planID =?";
                pstm1 = conn.prepareStatement(sql);
                pstm1.setInt(1, 1);
                pstm1.setInt(2, id);
                pstm1.executeUpdate();
                System.out.println("OK");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    public void startPlan() {
        if (getPlanId() == 0) {
            JOptionPane.showMessageDialog(null, "Pleas choose Plan");
        } else {
            System.out.println("Clicked Start Button");
            if (getPlanStatus() == 1) {
                System.out.println("No");
                showMessageDialog(null, "Your plan is starting!!");
            } else if (getPlanStatus() == 0) {
                Object[] options = {"OK", "Cancle"};
                int n = JOptionPane.showOptionDialog(deleteBtn,
                        "Do you want start plan?",
                        "Start Plan!!!",
                        JOptionPane.YES_NO_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        options[0]);
                if (n == 0) {
                    updateStatusPlan(getPlanId());
                    setVisible(false);
                    Home h1 = new Home();
                    h1.setVisible(true);
                    h1.pack();

                    System.out.println("stratPlanEnd");
                }
            }
        }
    }

    public void backToHome() {
        System.out.println("Clicked Home button");
        Home h = new Home();
        h.setVisible(true);
        h.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        h.setLocationRelativeTo(null);
        this.setVisible(false);
    }

    public void createMyPlan() {
        System.out.println("Clicked Create");
        CreatePlan cp = new CreatePlan();
        cp.setVisible(true);
        cp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        cp.setLocationRelativeTo(null);
        this.setVisible(false);
    }

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        showMyPlanTable();
    }//GEN-LAST:event_formWindowActivated

    private void myPlanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myPlanMouseClicked
        clickMyPlanTable();
    }//GEN-LAST:event_myPlanMouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        editMyPlan();
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        deleteMyPlan();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void addListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addListBtnActionPerformed
        addAddListToDetailOfMyPlan();
    }//GEN-LAST:event_addListBtnActionPerformed

    private void detailListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailListBtnActionPerformed
        clickToDetailList();
    }//GEN-LAST:event_detailListBtnActionPerformed

    private void lblAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddMouseClicked
        addAddListToDetailOfMyPlan();
    }//GEN-LAST:event_lblAddMouseClicked

    private void lblDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDetailMouseClicked
        clickToDetailList();
    }//GEN-LAST:event_lblDetailMouseClicked

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        startPlan();
    }//GEN-LAST:event_startBtnActionPerformed

    private void lblstartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblstartMouseClicked
        startPlan();
    }//GEN-LAST:event_lblstartMouseClicked

    private void lbleditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbleditMouseClicked
        editMyPlan();
    }//GEN-LAST:event_lbleditMouseClicked

    private void lbldeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldeleteMouseClicked
        deleteMyPlan();
    }//GEN-LAST:event_lbldeleteMouseClicked

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        backToHome();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        createMyPlan();
    }//GEN-LAST:event_createBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyPlan.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyPlan.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyPlan.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyPlan.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyPlan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addListBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton detailListBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblDPW;
    private javax.swing.JLabel lblDes;
    private javax.swing.JLabel lblDetail;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblPName;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblcreate;
    private javax.swing.JLabel lbldelete;
    private javax.swing.JLabel lbledit;
    private javax.swing.JLabel lblstart;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JTable myPlan;
    private javax.swing.JButton startBtn;
    private javax.swing.JLabel txtDPW;
    private javax.swing.JLabel txtDes;
    private javax.swing.JLabel txtEnd;
    private javax.swing.JLabel txtPName;
    private javax.swing.JLabel txtStart;
    private javax.swing.JLabel txtStatusPlan;
    // End of variables declaration//GEN-END:variables
}
